name: Generate Github Profile
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  github-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Profile Repositories
        uses: ntsd/github-profile-repositories@master
        with:
          github-token: "${{ secrets.GH_PAT }}"
          template-file: "./TEMPLATE.md"
          render-file: "./README.md"
          limit: 500
      - name: Commit files
        run: |
          git config --local user.email "ntsd@users.noreply.github.com"
          git config --local user.name "ntsd"
          git commit -am "docs: auto update README.md"
          git push
